#!/bin/bash

#PBS -S /bin/bash
#PBS -q gpuvolta
#PBS -l ncpus=48
#PBS -l ngpus=1
#PBS -l jobfs=50GB
#PBS -P fp0
#PBS -l mem=50GB
#PBS -l walltime=01:00:00
#PBS -N TF_RealData

cur_host=`hostname`
node_gpu=$((PBS_NGPUS / PBS_NNODES))
for node in `cat $PBS_NODEFILE | uniq`
do
    if [[ $node == $cur_host ]]
    then
       host_flag="${node}:${node_gpu}"
    else
       host_flag="${host_flag},${node}:${node_gpu}"
    fi
done

module load python3/3.11.7
module load use.own
module load compvis

datadir="/g/data/po67/zhijie/cub_datasets"
logdir="/home/561/zz8462/logs"

python3 /home/561/zz8462/source/cbm-loc-enhance/main.py --data-dir $datadir --log-dir $logdir
